Add one PhD student to authors (Mateusz)
pwr-ai/kio-website pull request #7
Opened 2020-11-18 14:18 UTC by rmhere

One PhD student added (with template to be filled)

2020-11-19 22:28 UTC, kajdanowicz requested changes
uzupełnij od razu swoją zawartość i dodatkowo podmień avatar.jpg na swoje zdjęcie

2020-11-19 22:28 UTC, kajdanowicz commented on content/en/authors/nurek/_index.md
> +- interest 3
wstaw od razu tutaj zawartość

2020-11-19 22:28 UTC, kajdanowicz commented on content/en/authors/nurek/_index.md
> +    year: 2008
wstaw od razu tutaj zawartość

2020-11-19 22:28 UTC, kajdanowicz commented on content/en/authors/nurek/_index.md
> +  link: https://github.com/
zrób update

2020-11-20 07:39 UTC, rmhere commented
@kajdanowicz , póki co robiłem tylko placeholder dla Mateusza (bo nie miał) - na tym planowałem skończyć swoją rolę w kwestii jego podstrony i przekazać mu pałeczkę do wypełnienia profilu. Poproszę Mateusza, aby uzupełnił rzeczy do tego brancha w takim razie.

2020-11-23 13:54 UTC, kajdanowicz approved these changes

2020-11-23 13:54 UTC, merged