Add Krzysztof Rajda page
pwr-ai/kio-website pull request #9
Opened 2020-11-19 14:02 UTC by xaru

2020-11-19 22:31 UTC, kajdanowicz commented on content/en/authors/rajda/_index.md
> +Krzysztof Rajda is a PhD Student of Computer Science at Department of Computational Intelligence, Wroclaw University of Science and Technology. He has received MSc in Computer Science from the Wrocla
wrzuć proszę linka do brand24

2020-11-19 22:31 UTC, kajdanowicz requested changes
super! dodaj link

2020-11-21 10:40 UTC, xaru commented
@kajdanowicz dodane ;)

2020-11-23 13:59 UTC, kajdanowicz approved these changes

2020-11-23 14:00 UTC, merged